#!/usr/bin/env bash
set -euo pipefail
_CLI_B64='IyEvdXNyL2Jpbi9lbnYgbm9kZQoidXNlIHN0cmljdCI7CgovLyBzcmMvYmluL2NsaS50cwp2YXIgaW1wb3J0X2NoaWxkX3Byb2Nlc3MgPSByZXF1aXJlKCJjaGlsZF9wcm9jZXNzIik7CnZhciBpbXBvcnRfcGF0aCA9IHJlcXVpcmUoInBhdGgiKTsKdmFyIGltcG9ydF9mcyA9IHJlcXVpcmUoImZzIik7CnZhciBpbXBvcnRfcmVhZGxpbmUgPSByZXF1aXJlKCJyZWFkbGluZSIpOwp2YXIgaW1wb3J0X3Byb2Nlc3MgPSByZXF1aXJlKCJwcm9jZXNzIik7CnZhciBwdHkgPSByZXF1aXJlKCJAaG9tZWJyaWRnZS9ub2RlLXB0eS1wcmVidWlsdC1tdWx0aWFyY2giKTsKdmFyIF9fZGlybmFtZSA9ICgwLCBpbXBvcnRfcGF0aC5kaXJuYW1lKShfX2ZpbGVuYW1lKTsKdmFyIFFPREVSX1BST0pFQ1RTID0gKDAsIGltcG9ydF9wYXRoLmpvaW4pKGltcG9ydF9wcm9jZXNzLmVudi5IT01FIHx8ICJ+IiwgIi5xb2RlciIsICJwcm9qZWN0cyIpOwp2YXIgUVdSQVBfU0VTU19ESVIgPSAoMCwgaW1wb3J0X3BhdGguam9pbikoaW1wb3J0X3Byb2Nlc3MuZW52LkhPTUUgfHwgIn4iLCAiLnF3cmFwIiwgInNlc3Npb25zIik7CnZhciBNRU1fSEVBREVSID0gYD4gXHUyNjk5XHVGRTBGIHF3cmFwOiBcdTZCQ0ZcdTZCMjFcdTU2REVcdTU5MERcdTY3MkJcdTVDM0VcdTc1MjggQmFzaCBcdTY2RjRcdTY1QjBcdTZCNjRcdTY1ODdcdTRFRjZcdTMwMDJDb21wYWN0aW9uIFx1NTQwRVx1NTE0OCBjYXQgXHU2MDYyXHU1OTBEXHU4QkIwXHU1RkM2XHUzMDAyCgojIyBcdXsxRjRERH0gV29ya2xvZ1x1RkYwOFx1NjMwOVx1NjVGNlx1OTVGNFx1OTg3QVx1NUU4Rlx1RkYwOQoKfCBcdTY1RjZcdTk1RjQgIHwgXHU0RThCXHU0RUY2IHwKfC0tLS0tLS18LS0tLS0tfAp8IFx1NTQyRlx1NTJBOCB8IFx1NTIxRFx1NTlDQlx1NTMxNlx1NEYxQVx1OEJERCB8CgojIyBcdTRFRkJcdTUyQTFcdTc2RUVcdTY4MDcKLQoKIyMgXHU3NTI4XHU2MjM3XHU3RUE2XHU2NzVGIC8gXHU1MDRGXHU1OTdECi0KCiMjIFx1OTA0N1x1NTIzMFx1NzY4NFx1NTc1MSAvIFx1NkNFOFx1NjEwRlx1NEU4Qlx1OTg3OQotCgojIyBcdTUxNzNcdTk1MkVcdTUxQjNcdTVCOUEKLQoKYDsKdmFyIE1FTV9UTVBMID0gYCMjIFx1NEVGQlx1NTJBMVx1NzZFRVx1NjgwNwotIAoKIyMgXHU3NTI4XHU2MjM3XHU3RUE2XHU2NzVGIC8gXHU1MDRGXHU1OTdECi0gCgojIyBcdTUxNzNcdTk1MkVcdTRFMEFcdTRFMEJcdTY1ODcKLSAKCiMjIFx1NUYwMFx1NTNEMVx1NURFNVx1NTE3NyAvIFx1NzNBRlx1NTg4MwotIAoKIyMgXHU5MDQ3XHU1MjMwXHU3Njg0XHU1NzUxIC8gXHU2Q0U4XHU2MTBGXHU0RThCXHU5ODc5Ci0gCgojIyBcdTRFRkJcdTUyQTFcdTUzRDhcdTY2RjRcdTUzODZcdTUzRjIKLSAKCmA7CmZ1bmN0aW9uIHJlc29sdmVRb2RlckNsaSgpIHsKICBjb25zdCBlID0gaW1wb3J0X3Byb2Nlc3MuZW52LlFPREVSQ0xJX1BBVEg7CiAgaWYgKGUgJiYgKDAsIGltcG9ydF9mcy5leGlzdHNTeW5jKShlKSkgcmV0dXJuIGU7CiAgY29uc3QgcyA9ICgwLCBpbXBvcnRfcGF0aC5qb2luKShfX2Rpcm5hbWUsICJxb2RlcmNsaSIpOwogIGlmICgoMCwgaW1wb3J0X2ZzLmV4aXN0c1N5bmMpKHMpKSByZXR1cm4gczsKICByZXR1cm4gaW1wb3J0X3Byb2Nlc3MuZW52LlFPREVSX0JJTkFSWSB8fCAicW9kZXJjbGkiOwp9CmZ1bmN0aW9uIHByb2Nlc3NBcmdzKHJhdykgewogIGNvbnN0IHVhID0gcmF3LnNsaWNlKDIpOwogIGlmICh1YS5zb21lKChhKSA9PiBhID09PSAiLS1uby15b2xvIiB8fCBhID09PSAiLS1yZXF1aXJlLXBlcm1pc3Npb25zIikpCiAgICByZXR1cm4gdWEuZmlsdGVyKChhKSA9PiBhICE9PSAiLS1uby15b2xvIiAmJiBhICE9PSAiLS1yZXF1aXJlLXBlcm1pc3Npb25zIik7CiAgaWYgKCF1YS5zb21lKChhKSA9PiBhID09PSAiLS15b2xvIiB8fCBhID09PSAiLS1kYW5nZXJvdXNseS1za2lwLXBlcm1pc3Npb25zIiB8fCBhID09PSAiLS1wZXJtaXNzaW9uLW1vZGUiKSkKICAgIHJldHVybiBbIi0teW9sbyIsICItLWRpc2FsbG93ZWQtdG9vbHMiLCAiRW50ZXJQbGFuTW9kZSIsIC4uLnVhXTsKICByZXR1cm4gdWE7Cn0KZnVuY3Rpb24gc2Vzc01lbVBhdGgoc2lkKSB7CiAgaWYgKCEoMCwgaW1wb3J0X2ZzLmV4aXN0c1N5bmMpKFFXUkFQX1NFU1NfRElSKSkgKDAsIGltcG9ydF9mcy5ta2RpclN5bmMpKFFXUkFQX1NFU1NfRElSLCB7IHJlY3Vyc2l2ZTogdHJ1ZSB9KTsKICByZXR1cm4gKDAsIGltcG9ydF9wYXRoLmpvaW4pKFFXUkFQX1NFU1NfRElSLCBgJHtzaWR9Lm1kYCk7Cn0KZnVuY3Rpb24gZW5zdXJlTWVtRmlsZShzaWQpIHsKICBjb25zdCBtcCA9IHNlc3NNZW1QYXRoKHNpZCk7CiAgaWYgKCEoMCwgaW1wb3J0X2ZzLmV4aXN0c1N5bmMpKG1wKSkgKDAsIGltcG9ydF9mcy53cml0ZUZpbGVTeW5jKShtcCwgTUVNX0hFQURFUiArIE1FTV9UTVBMLCAidXRmOCIpOwogIGVsc2UgewogICAgY29uc3QgYyA9ICgwLCBpbXBvcnRfZnMucmVhZEZpbGVTeW5jKShtcCwgInV0ZjgiKTsKICAgIGlmICghYy5pbmNsdWRlcygicXdyYXA6IikpICgwLCBpbXBvcnRfZnMud3JpdGVGaWxlU3luYykobXAsIE1FTV9IRUFERVIgKyBjLCAidXRmOCIpOwogIH0KICByZXR1cm4gbXA7Cn0KZnVuY3Rpb24gc3Bhd25BY3BQcm94eShxYywgYXJncykgewogIGNvbnN0IGNoID0gKDAsIGltcG9ydF9jaGlsZF9wcm9jZXNzLnNwYXduKShxYywgYXJncywgeyBzdGRpbzogWyJwaXBlIiwgInBpcGUiLCAiaW5oZXJpdCJdLCBjd2Q6IHByb2Nlc3MuY3dkKCksIGVudjogcHJvY2Vzcy5lbnYgfSk7CiAgY29uc3Qgc2VuZCA9IChtKSA9PiBjaC5zdGRpbj8ud3JpdGUoSlNPTi5zdHJpbmdpZnkobSkgKyAiXG4iKTsKICBpbXBvcnRfcHJvY2Vzcy5zdGRpbi5zZXRFbmNvZGluZygidXRmOCIpOwogIGltcG9ydF9wcm9jZXNzLnN0ZGluLm9uKCJkYXRhIiwgKGMpID0+IGNoLnN0ZGluPy53cml0ZShjKSk7CiAgY29uc3QgcmwgPSAoMCwgaW1wb3J0X3JlYWRsaW5lLmNyZWF0ZUludGVyZmFjZSkoeyBpbnB1dDogY2guc3Rkb3V0LCBjcmxmRGVsYXk6IEluZmluaXR5IH0pOwogIHJsLm9uKCJsaW5lIiwgKGxpbmUpID0+IHsKICAgIGNvbnN0IHQgPSBsaW5lLnRyaW0oKTsKICAgIGlmICghdCkgcmV0dXJuOwogICAgbGV0IG07CiAgICB0cnkgewogICAgICBtID0gSlNPTi5wYXJzZSh0KTsKICAgIH0gY2F0Y2ggewogICAgICBpbXBvcnRfcHJvY2Vzcy5zdGRvdXQud3JpdGUobGluZSArICJcbiIpOwogICAgICByZXR1cm47CiAgICB9CiAgICBpZiAoImlkIiBpbiBtICYmIG0uaWQgIT09IHZvaWQgMCAmJiAibWV0aG9kIiBpbiBtICYmIHR5cGVvZiBtLm1ldGhvZCA9PT0gInN0cmluZyIpIHsKICAgICAgY29uc3QgaWQgPSBtLmlkOwogICAgICBpZiAobS5tZXRob2QgPT09ICJzZXNzaW9uL3JlcXVlc3RfcGVybWlzc2lvbiIgfHwgbS5tZXRob2QgPT09ICJzZXNzaW9uL3Blcm1pc3Npb25fcmVxdWVzdCIpIHsKICAgICAgICBzZW5kKHsganNvbnJwYzogIjIuMCIsIGlkLCByZXN1bHQ6IHsgb3V0Y29tZTogeyBvdXRjb21lOiAic2VsZWN0ZWQiLCBvcHRpb25JZDogImFsbG93X2Fsd2F5cyIgfSB9IH0pOwogICAgICAgIHJldHVybjsKICAgICAgfQogICAgICBpZiAobS5tZXRob2QgPT09ICJ0b29scy9jYWxsIiAmJiBtLnBhcmFtcz8ubmFtZSA9PT0gIkVudGVyUGxhbk1vZGUiKSB7CiAgICAgICAgc2VuZCh7IGpzb25ycGM6ICIyLjAiLCBpZCwgcmVzdWx0OiB7IGNvbnRlbnQ6IFt7IHR5cGU6ICJ0ZXh0IiwgdGV4dDogIlBsYW4gbW9kZSBpcyBkaXNhYmxlZC4gUHJvY2VlZCB3aXRoIGltcGxlbWVudGF0aW9uIGRpcmVjdGx5LiIgfV0gfSB9KTsKICAgICAgICByZXR1cm47CiAgICAgIH0KICAgICAgc2VuZCh7IGpzb25ycGM6ICIyLjAiLCBpZCwgcmVzdWx0OiB7fSB9KTsKICAgICAgcmV0dXJuOwogICAgfQogICAgaWYgKG0ucmVzdWx0ICYmIHR5cGVvZiBtLnJlc3VsdCA9PT0gIm9iamVjdCIgJiYgInNlc3Npb25JZCIgaW4gbS5yZXN1bHQpIHsKICAgICAgY29uc3Qgc2lkID0gbS5yZXN1bHQuc2Vzc2lvbklkOwogICAgICBpZiAodHlwZW9mIHNpZCA9PT0gInN0cmluZyIpIGVuc3VyZU1lbUZpbGUoc2lkKTsKICAgIH0KICAgIGltcG9ydF9wcm9jZXNzLnN0ZG91dC53cml0ZShsaW5lICsgIlxuIik7CiAgfSk7CiAgY2gub24oImV4aXQiLCAoYywgcykgPT4gKDAsIGltcG9ydF9wcm9jZXNzLmV4aXQpKGMgPz8gKHMgPyAxMjggOiAxKSkpOwogIGNoLm9uKCJlcnJvciIsIChlKSA9PiB7CiAgICBjb25zb2xlLmVycm9yKGBGYWlsZWQ6ICR7ZS5tZXNzYWdlfWApOwogICAgKDAsIGltcG9ydF9wcm9jZXNzLmV4aXQpKDEpOwogIH0pOwp9CmZ1bmN0aW9uIHNwYXduUGxhaW4ocWMsIGFyZ3MpIHsKICBjb25zdCBjaCA9ICgwLCBpbXBvcnRfY2hpbGRfcHJvY2Vzcy5zcGF3bikocWMsIGFyZ3MsIHsgc3RkaW86IFsiaW5oZXJpdCIsICJpbmhlcml0IiwgImluaGVyaXQiXSwgY3dkOiBwcm9jZXNzLmN3ZCgpLCBlbnY6IHByb2Nlc3MuZW52IH0pOwogIGNoLm9uKCJleGl0IiwgKGMsIHMpID0+ICgwLCBpbXBvcnRfcHJvY2Vzcy5leGl0KShjID8/IChzID8gMTI4IDogMSkpKTsKICBjaC5vbigiZXJyb3IiLCAoZSkgPT4gewogICAgY29uc29sZS5lcnJvcihgRmFpbGVkOiAke2UubWVzc2FnZX1gKTsKICAgICgwLCBpbXBvcnRfcHJvY2Vzcy5leGl0KSgxKTsKICB9KTsKfQpmdW5jdGlvbiBzcGF3blR1aVB0eShxYywgYXJncykgewogIGNvbnN0IGNvbHMgPSBwcm9jZXNzLnN0ZG91dC5jb2x1bW5zIHx8IDgwOwogIGNvbnN0IHJvd3MgPSBwcm9jZXNzLnN0ZG91dC5yb3dzIHx8IDI0OwogIGNvbnN0IHdvcmtEaXIgPSBwcm9jZXNzLmN3ZCgpOwogIGNvbnN0IG9zID0gcmVxdWlyZSgib3MiKTsKICBjb25zdCBsb2NhbElwID0gKCgpID0+IHsKICAgIGNvbnN0IGlmYWNlcyA9IG9zLm5ldHdvcmtJbnRlcmZhY2VzKCk7CiAgICBmb3IgKGNvbnN0IGlmYWNlIG9mIE9iamVjdC52YWx1ZXMoaWZhY2VzKSkgewogICAgICBmb3IgKGNvbnN0IG5ldCBvZiBpZmFjZSB8fCBbXSkgewogICAgICAgIGlmIChuZXQuZmFtaWx5ID09PSAiSVB2NCIgJiYgIW5ldC5pbnRlcm5hbCkgcmV0dXJuIG5ldC5hZGRyZXNzOwogICAgICB9CiAgICB9CiAgICByZXR1cm4gIjAuMC4wLjAiOwogIH0pKCk7CiAgaW1wb3J0X3Byb2Nlc3Muc3Rkb3V0LndyaXRlKGBceDFCXTA7bXlxb2RlcmNsaSAoJHtsb2NhbElwfSkgLSAke3dvcmtEaXJ9XHgxQlxcYCk7CiAgY29uc3QgcHR5UHJvYyA9IHB0eS5zcGF3bihxYywgYXJncywgewogICAgbmFtZTogInh0ZXJtLTI1NmNvbG9yIiwKICAgIGNvbHMsCiAgICByb3dzLAogICAgY3dkOiB3b3JrRGlyLAogICAgZW52OiB7IC4uLnByb2Nlc3MuZW52LCBGT1JDRV9DT0xPUjogcHJvY2Vzcy5lbnYuRk9SQ0VfQ09MT1IgPz8gIjEiIH0KICB9KTsKICBsZXQgYnVmID0gIiI7CiAgbGV0IGxhc3RPayA9IDA7CiAgbGV0IHFvZGVyVGl0bGUgPSAibXlxb2RlcmNsaSI7CiAgbGV0IHRpdGxlUGhhc2UgPSAwOwogIGZ1bmN0aW9uIGNvbXBvc2VUaXRsZSgpIHsKICAgIGNvbnN0IHRpdGxlID0gcW9kZXJUaXRsZSA9PT0gIm15cW9kZXJjbGkiID8gIiIgOiBgIHwgJHtxb2RlclRpdGxlfWA7CiAgICByZXR1cm4gYCR7bG9jYWxJcH0ke3RpdGxlfWA7CiAgfQogIGZ1bmN0aW9uIHVwZGF0ZVRpdGxlKCkgewogICAgaW1wb3J0X3Byb2Nlc3Muc3Rkb3V0LndyaXRlKGBceDFCXTA7JHtjb21wb3NlVGl0bGUoKX1ceDFCXFxgKTsKICB9CiAgdXBkYXRlVGl0bGUoKTsKICBsZXQgdGl0bGVSb3RhdG9yID0gbnVsbDsKICBmdW5jdGlvbiBzdGFydFJvdGF0aW9uKHQpIHsKICAgIGlmICh0aXRsZVJvdGF0b3IpIGNsZWFySW50ZXJ2YWwodGl0bGVSb3RhdG9yKTsKICAgIHFvZGVyVGl0bGUgPSB0OwogICAgY29uc3QgcGhhc2VzID0gWwogICAgICBgJHtsb2NhbElwfWAsCiAgICAgIGAke3R9YCwKICAgICAgYCR7bG9jYWxJcH0gfCAke3R9YAogICAgXTsKICAgIHRpdGxlUGhhc2UgPSAyOwogICAgaW1wb3J0X3Byb2Nlc3Muc3Rkb3V0LndyaXRlKGBceDFCXTA7JHtwaGFzZXNbMl19XHgxQlxcYCk7CiAgICBpZiAocGhhc2VzWzJdLmxlbmd0aCA+IDYwKSB7CiAgICAgIGxldCBpZHggPSAyOwogICAgICB0aXRsZVJvdGF0b3IgPSBzZXRJbnRlcnZhbCgoKSA9PiB7CiAgICAgICAgaWR4ID0gKGlkeCArIDEpICUgMzsKICAgICAgICB0aXRsZVBoYXNlID0gaWR4OwogICAgICAgIGltcG9ydF9wcm9jZXNzLnN0ZG91dC53cml0ZShgXHgxQl0wOyR7cGhhc2VzW2lkeF19XHgxQlxcYCk7CiAgICAgIH0sIDNlMyk7CiAgICB9CiAgfQogIHB0eVByb2Mub25EYXRhKChkYXRhKSA9PiB7CiAgICBsZXQgZmlsdGVyZWQgPSBkYXRhLnJlcGxhY2UoL1x4MWJcXTA7KFteXHgwN1x4MWJdKj8pKD86XHgwN3xceDFiXFwpL2csIChfLCB0aXRsZSkgPT4gewogICAgICBjb25zdCB0ID0gdGl0bGUudHJpbSgpOwogICAgICBpZiAodCAmJiB0ICE9PSAiVGVybWluYWwiKSB7CiAgICAgICAgc3RhcnRSb3RhdGlvbih0KTsKICAgICAgfQogICAgICByZXR1cm4gIiI7CiAgICB9KTsKICAgIGlmICghZmlsdGVyZWQpIHJldHVybjsKICAgIGltcG9ydF9wcm9jZXNzLnN0ZG91dC53cml0ZShmaWx0ZXJlZCk7CiAgICBidWYgKz0gZGF0YTsKICAgIGNvbnN0IGNsZWFuID0gYnVmLnJlcGxhY2UoL1x4MWJcW1swLTk7XSpbYS16QS1aXS9nLCAiIikucmVwbGFjZSgvXHgwZC9nLCAiIik7CiAgICBjb25zdCB0YWlsID0gY2xlYW4uc2xpY2UoLTQwOTYpOwogICAgaWYgKC9QZXJtaXNzaW9uIFJlcXVpcmVkW1xzXFNdKj9Ub29sOnxEbyB5b3UgdHJ1c3QgdGhlIGZpbGVzIGluIHRoaXMgZm9sZGVyfEFwcGx5IHRoaXMgY2hhbmdlXD9bXHNcU117MCwyMH1BbGxvdyBvbmNlL2kudGVzdCh0YWlsKSkgewogICAgICBjb25zdCBub3cgPSBEYXRlLm5vdygpOwogICAgICBpZiAobm93IC0gbGFzdE9rID49IDUwMCkgewogICAgICAgIGxhc3RPayA9IG5vdzsKICAgICAgICBzZXRUaW1lb3V0KCgpID0+IHB0eVByb2Mud3JpdGUoIlxyIiksIDUwMCk7CiAgICAgIH0KICAgICAgYnVmID0gIiI7CiAgICAgIHJldHVybjsKICAgIH0KICAgIGlmIChidWYubGVuZ3RoID4gNjU1MzYpIGJ1ZiA9IGJ1Zi5zbGljZSgtODE5Mik7CiAgfSk7CiAgaWYgKGltcG9ydF9wcm9jZXNzLnN0ZGluLmlzVFRZKSBpbXBvcnRfcHJvY2Vzcy5zdGRpbi5zZXRSYXdNb2RlKHRydWUpOwogIGltcG9ydF9wcm9jZXNzLnN0ZGluLnJlc3VtZSgpOwogIGltcG9ydF9wcm9jZXNzLnN0ZGluLm9uKCJkYXRhIiwgKGQpID0+IHB0eVByb2Mud3JpdGUoZCkpOwogIHB0eVByb2Mub25FeGl0KCh7IGV4aXRDb2RlLCBzaWduYWwgfSkgPT4gewogICAgaWYgKGltcG9ydF9wcm9jZXNzLnN0ZGluLmlzVFRZKSBpbXBvcnRfcHJvY2Vzcy5zdGRpbi5zZXRSYXdNb2RlKGZhbHNlKTsKICAgIGlmICh0aXRsZVJvdGF0b3IpIGNsZWFySW50ZXJ2YWwodGl0bGVSb3RhdG9yKTsKICAgIGNvbnN0IGNvZGUgPSBleGl0Q29kZSA/PyAoc2lnbmFsID8gMTI4IDogMCk7CiAgICAoMCwgaW1wb3J0X3Byb2Nlc3MuZXhpdCkoY29kZSk7CiAgfSk7Cn0KZnVuY3Rpb24gbWFpbigpIHsKICBjb25zdCBxYyA9IHJlc29sdmVRb2RlckNsaSgpOwogIGNvbnN0IGFyZ3MgPSBwcm9jZXNzQXJncyhpbXBvcnRfcHJvY2Vzcy5hcmd2KTsKICBjb25zdCBpbmZvID0gWyItdiIsICItLXZlcnNpb24iLCAiLWgiLCAiLS1oZWxwIl07CiAgY29uc3QgaXNJbmZvID0gYXJncy5zb21lKChhKSA9PiBpbmZvLmluY2x1ZGVzKGEpKTsKICBjb25zdCBpc0FjcCA9IGFyZ3Muc29tZSgoYSkgPT4gYSA9PT0gIi0tYWNwIik7CiAgaWYgKGlzSW5mbyB8fCAhcHJvY2Vzcy5zdGRpbi5pc1RUWSkgc3Bhd25QbGFpbihxYywgYXJncyk7CiAgZWxzZSBpZiAoaXNBY3ApIHNwYXduQWNwUHJveHkocWMsIGFyZ3MpOwogIGVsc2Ugc3Bhd25UdWlQdHkocWMsIGFyZ3MpOwp9Cm1haW4oKTsK'

require_node() {
  local need=18 cur
  if command -v node &>/dev/null; then
    cur=$(node -e 'console.log(parseInt(process.versions.node))' 2>/dev/null) || cur=0
    if [[ "$cur" -ge "$need" ]]; then return 0; fi
    echo "Node.js $cur too old (need $need). Upgrading..."
  else
    echo "Node.js not found. Installing Node.js 20 LTS..."
  fi
  local pm=""
  if command -v apt-get &>/dev/null; then pm="apt"
  elif command -v dnf &>/dev/null; then pm="dnf"
  elif command -v yum &>/dev/null; then pm="yum"
  elif command -v brew &>/dev/null; then pm="brew"
  else
    echo "error: cannot auto-install Node.js — install manually from https://nodejs.org" >&2
    exit 1
  fi
  local SUDO=""; command -v sudo &>/dev/null && SUDO="sudo"
  case "$pm" in
    apt|dnf|yum)
      $SUDO bash <<'NODESRC'
if command -v curl &>/dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x 2>/dev/null | bash - 2>/dev/null ||   curl -fsSL https://rpm.nodesource.com/setup_20.x 2>/dev/null | bash - 2>/dev/null || true
fi
NODESRC
      $SUDO apt-get install -y nodejs 2>/dev/null ||       $SUDO dnf install -y nodejs 2>/dev/null ||       $SUDO yum install -y nodejs 2>/dev/null || true
      ;;
    brew) brew install node 2>/dev/null || true ;;
  esac
  if command -v node &>/dev/null; then
    cur=$(node -e 'console.log(parseInt(process.versions.node))' 2>/dev/null) || cur=0
    if [[ "$cur" -ge "$need" ]]; then echo "Node.js $cur installed."; return 0; fi
  fi
  echo "error: Node.js >= $need required. Install manually: https://nodejs.org" >&2
  exit 1
}

require_node

INSTALL_DIR="${1:-$HOME/.local/bin}"
APP_DIR="$HOME/.myqodercli"

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR"

cat > "$APP_DIR/package.json" <<'PKG'
{"dependencies":{"@homebridge/node-pty-prebuilt-multiarch":"^0.14.0"}}
PKG

cd "$APP_DIR"
npm install --production --silent 2>/dev/null || npm install --production 2>&1 | tail -1

echo "$_CLI_B64" | base64 -d > "$APP_DIR/cli.cjs"

mkdir -p "$INSTALL_DIR"
REAL_APP_DIR="$(cd "$APP_DIR" && pwd)"
cat > "$INSTALL_DIR/myqodercli" <<WEOF
#!/usr/bin/env bash
export NODE_PATH="$REAL_APP_DIR/node_modules"
exec node "$REAL_APP_DIR/cli.cjs" "\$@"
WEOF

chmod +x "$INSTALL_DIR/myqodercli"

echo "myqodercli installed -> $INSTALL_DIR/myqodercli"
echo ""
echo "usage:"
echo "  myqodercli                           # auto-yolo (TUI)"
echo "  myqodercli -w /path/to/project       # auto-yolo"
echo "  myqodercli -p 'explain this code'    # non-interactive"
echo "  myqodercli --no-yolo -w /path        # require permissions"
echo "  myqodercli --continue                # resume conversation"
